language: ruby
rvm: 2.3.0
env: RAILS_ENV=test
before_script:
 - psql -c 'create database api_flashcards_test;' -U postgres
 - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
 - cat spec/dummy/config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec